# -*- coding: utf-8 -*-
"""DataTransform_VehicleData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FpNzym6unmxeWJ1AR3Byszm_NaK0rvJM
"""

from google.colab import files
import pandas as pd
import os

uploaded = files.upload()

vehicle_df = pd.read_csv("bc_veh4223_230215.csv")
vehicle_df.head()

vehicle_df['OPD_DATE'] = pd.to_datetime(vehicle_df['OPD_DATE'], format='%d%b%Y:%H:%M:%S')
vehicle_df['ACT_TIME'] = pd.to_timedelta(vehicle_df['ACT_TIME'], unit='s')

vehicle_df['TIMESTAMP'] = vehicle_df['OPD_DATE'] + vehicle_df['ACT_TIME']

print("\nThe Data Frame for Feb 15th 2023 for the vehicle - 4223 after adding the Time Stamp column :")
vehicle_df.head()

vehicle_df['dMETERS'] = vehicle_df['METERS'].diff()
vehicle_df['dTIMESTAMP'] = vehicle_df['TIMESTAMP'].diff().dt.total_seconds()

vehicle_df['SPEED'] = vehicle_df.apply( lambda row: row['dMETERS'] / row['dTIMESTAMP'] if pd.notna(row['dTIMESTAMP']) else None, axis=1 )

print("\nThe Data Frame for Feb 15th 2023 for the vehicle - 4223 after adding the Speed column : ")
vehicle_df.head()

trip_status = vehicle_df.groupby('EVENT_NO_TRIP')['SPEED'].agg(['max', 'median'])

max_trip = trip_status.loc[trip_status['max'].idxmax()]
max_speed = max_trip['max']
max_speed_record = vehicle_df[vehicle_df['SPEED'] == max_speed].iloc[0]

print(f"\n The minimum speed for Feb 15th 2023 for the vehicle - 4223 : {max_speed} m/s" )
print(f"\n The Location ,Longitude, Latitude and time of max speed for Feb 15th 2023 for the vehicle - 4223 : ", max_speed_record['GPS_LONGITUDE'], max_speed_record['GPS_LATITUDE'], max_speed_record['TIMESTAMP'])
print(f"\n The median speed for Feb 15th 2023 for the vehicle - 4223 : {trip_status['median'].median()} m/s")