# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iD-XCQ6xpAvhyDvCvyWaXcAEvKBms6D-
"""

#Imported the required packages
import requests
import json
from datetime import datetime, timedelta

#API Key retrieved for Open Weather API
api_key = "46fe0967e705191c2b113a406c341ce0"

#Link to the application
base_url = "http://api.openweathermap.org/data/2.5/weather?"

#Dynamically takes the input and forms the complete url
city_name = input("Enter city name : ")
complete_url = base_url + "appid=" + api_key + "&q=" + city_name

#Response is being collected and converted to json
response = requests.get(complete_url)
current_response = response.json()

#Status check condition for rain currently
current_rainstatus = any(w['main'] == 'Rain' for w in current_response['weather'])

#Defining timeperiod and forming the url accordingly
future_days = datetime.utcnow() + timedelta(days=3)
forecast_url = base_url + f'q={city_name}&appid={api_key}&dt={int(future_days.timestamp())}'

#Response is being collected and converted to json
fresponse = requests.get(forecast_url)
forecast_response = fresponse.json()

#Status check condition for rain for coming 3 days
forecast_rainstatus = any(w['main'] == 'Rain' for w in forecast_response['weather'])

#Printing the status based on the rain situation in the city requested by user
print(f"If you are wondering if it's raining in {city_name} now !? \n {'Yes it is !! Enjoy the cool weather' if current_rainstatus else 'No, time for some outdoor fun'}")
print(f"Is it forecasted to be raining in {city_name} the coming 3 days !? \n {'Yes it is !! Plan your holiday' if forecast_rainstatus else 'No, you are good off without an umbrella :P'}")